[mongodb]
mongodb-dev.nemani.online

[catalogue]
catalogue-dev.nemani.online

[redis]
redis-dev.nemani.online

[user]
user-dev.nemani.online

[cart]
cart-dev.nemani.online

[mysql]
mysql-dev.nemani.online

[shipping]
shipping-dev.nemani.online

[payment]
payment-dev.nemani.online

[rabbitmq]
rabbitmq-dev.nemani.online

[frontend]
frontend-dev.nemani.online


[all:vars] 
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.nemani.online
REDIS_HOST=redis-dev.nemani.online
USER_HOST=user-dev.nemani.online
CATALOGUE_HOST=catalogue-dev.nemani.online
MYSQL_HOST=mysql-dev.nemani.online
SHIPPING_HOST=shipping-dev.nemani.online
PAYMENT_HOST=payment-dev.nemani.online
RABBITMQ_HOST=payment-dev.nemani.online
CART_HOST=cart-dev.nemani.online




