[mongodb]
mongodb-dev.nemani.online

[catalogue]
catalogue-dev.nemani.online

[redis]
redis-dev.nemani.online

[user]
user-dev.nemani.online

[cart]
cart-dev.nemani.online




[all:vars] 
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.nemani.online