- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars: 
    sg_id: sg-0f1ebec62fce41ad5
    ami_id: ami-0220d79f3f480ecf5
    environ: dev
    instances: 
    - mongodb
    - catalogue
    domain_name: nemani.online
    action: create
  tasks: 
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}-{{ environ }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags: 
        project: roboshop
        Component: "{{ item }}"
        Environment: "{{ environ }}"
        Name: "{{ item }}-{{ environ }}"
    loop: "{{ instances }}"
    register: ec2_output
    when: action == "create"

  - name: print ec2 output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
    when: action == "create"


  - name: create r53 records
    amazon.aws.route53:
      state: present
      record: "{{ item.item }}-{{ environ }}.{{ domain_name }}" #mongodb-dev.nemani.online      #hete item is first loop under results - mongodb is an item in that so we are calling as item.item line#233 in output file
      zone: "{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}" #here instances is list so we have to access by [0]
      wait: true
    loop: "{{ ec2_output.results }}"
    when: action == "create"

  - name: create r53 records for frontend
    amazon.aws.route53:
      state: present
      record: "roboshop-{{ environ }}.{{ domain_name }}" #roboshop-dev.nemani.online      #hete item is first loop under results - mongodb is an item in that so we are calling as item.item line#233 in output file
      zone: "{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}" #here instances is list so we have to access by [0]
      wait: true
    loop: "{{ ec2_output.results }}"
    when: #and gate both shold bve true
    - item.item == "frontend"
    - action == "create"

  - name: delete ec2 instance
    amazon.aws.ec2_instance: 
      state: absent
      name: "{{ item }}-{{ environ }}"
    loop: "{{ instances }}"